### ISSUE TITLE
Can't get proxytunnel to work

### ISSUE THREAD

**Issue by HazCod** [proxytunnel/proxytunnel#10]
Hello,

I can't seem to get proxytunnel to work on my apache vhost. My remote server has an SSH daemon running on port 2234 and an apache on 80/443.

VHOST CONFIG

```
<VirtualHost *:443>
  ServerName connect.website.com

  SSLEngine On
  SSLCertificateFile /etc/ssl/cert.pem
  SSLCertificateKeyFile /etc/ssl/privkey.pem
  SSLCertificateChainFile /etc/ssl/fullchain.pem

  #HostnameLookups on
  ProxyRequests On
  ProxyVia on

  AllowCONNECT 2234 #SSH ON 2234

#  <Proxy *>
#    Order deny,allow
#    Deny from all
#  </Proxy>
#  <Proxy 127.0.0.1>
#    Order deny,allow
#    Allow from all
#  </Proxy>

  DocumentRoot /var/www/connect
</VirtualHost>
```

SSH CONFIG

```
Host hazcod
  ServerAliveInterval 30
  ProxyCommand proxytunnel -v -X -p proxy.company.com:3128 -P 'companyuser:companypass' -r connect.website.com:443 -d 127.0.0.1:2234 -H "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)"
```

LOG

```
hazcod@django:~$ ssh hazcod
SSL local to remote proxy enabled
Local proxy proxy.company.com resolves to 2.xxx.xxx.xxx
Connected to proxy.companycom:3128 (local proxy)

Tunneling to connect.website.com:443 (remote proxy)
Communication with local proxy:
 -> CONNECT connect.website.com:443 HTTP/1.0
 -> Proxy-Authorization: Basic xxxxx=
 -> Proxy-Connection: Keep-Alive
 -> User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)
 <- HTTP/1.1 200 Connection established

Tunneling to 127.0.0.1:2234 (destination)
Communication with remote proxy:
 -> CONNECT 127.0.0.1:2234 HTTP/1.0
 -> Proxy-Connection: Keep-Alive
 -> User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)
error: Socket write error.
```

Any ideas? I think it's strange he is trying to do a `CONNECT 127.0.0.1:2234 HTTP/1.0` instead of a SSH client connect.. Thanks.
Regards

**Comment by blinkingtwelve** [comment]
Version? Have you tried main head?

**Comment by HazCod** [comment]
@blinkingtwelve proxytunnel 1.9.0 (rev 242)

**Comment by blinkingtwelve** [comment]
If you don't know whether you're using main head then you're probably not ;-)

Anyhow, I think you might have switched the remote proxy and the proxy parameters.

**Comment by HazCod** [comment]
I do? Local proxy ~ company proxy and Remote proxy ~ server with SSHD running apache2 on 443

**Comment by blinkingtwelve** [comment]
Yeah you're right.

The config which works well for me is:

Host mySSHshorthand
        Hostname hostname-as-named-in-cert-and-as-visible-from-the-proxy
        ProxyCommand proxytunnel -v --remproxy=same_host_as_in_Hostname:443 --dest=%h:%p --encrypt-remproxy -H "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)\n"

Which is very similar to yours. Vhost config is also similar. I'm taking the proxy from the environment variables though.

Some more ideas:
- You could try analyzing (tcpdump) the initial traffic between the remote proxy and the SSH server
- You could try tunneling through your own local proxy first (assuming proxy.company.com is not under your control), this gives you more debugging options.
- And you could go through the changelog to see if the current version would solve your issue (you're not completely up to date).

**Comment by HazCod** [comment]
Building and installing from latest git fixed it! Thanks!

**Comment by sigio** [comment]
@HazCod the sourceforge version is the same... we just moved to github to ease development.

**Comment by suen** [comment]
Had same problem. In my case the culprit was the local proxy, resolved it by using -X option to encrypt between 1st and 2nd proxy using SSL.
