### ISSUE TITLE
Issue in ProxyTunnel Behaviour on HTTPS proxy

### ISSUE THREAD

**Issue by Resousse** [proxytunnel/proxytunnel#13]
Hello,
Firstly, I would like to thank proxytunnel owner and contributor for this wonderful tool!

Few years ago, it was working like a charm, but after lot of updates (Apache, ssh), it stopped to work:

To explain the issue: If I do a "openssl s_client -connect" on the my https server on port 443 with the following command 
```
CONNECT localhost:22 HTTP/1.0
Proxy-Connection: Keep-Alive
```
I get the response "HTTP/1.0 200 Connection Established" as expected.

But if I do the following 
`proxytunnel.exe -v -E -p www.mywebsite.com:443 -d localhost:22`
I get 
```
Tunneling to localhost:22 (destination)
Communication with local proxy:
 -> CONNECT localhost:22 HTTP/1.0
 -> Proxy-Connection: Keep-Alive
error: Socket write error.
```
As you can see, I copied the same Connect and proxy-connection instructions in the openssl shell and I got a different result.
My ProxyTunnel version is 1.9.0 (rev 224) and it's the lastest one.
I used the compiled binary, and I'm pretty affraid that someone will ask me to get the repo and do the compilation... :(

Would you know what could be the problem? (I'm pretty sure my server-side apache configuration is good)
Thanks & regards

**Comment by Resousse** [comment]
I finally got the master repo and installed cygwin + dependencies (openssl, make, gcc) and get it compiled.
Now it works!
Is it possible to publish an up-to-date windows version on your website? :smiley: 
Thanks

**Comment by dagwieers** [comment]
I guess we should, I think @sigio did the Windows builds.
v1.9.1 needs some love before we can do a release.

**Comment by sigio** [comment]
I don't really have any access to windows systems anymore...

**Comment by dagwieers** [comment]
Here's hoping that now that Microsoft is changing, maybe they have free build infrastructure ?
Or how about using MinGW ? Is that even possible ?

**Comment by nick-wellinghoff-sp** [comment]
@DevilSOF did you ever figure this out? I am getting the same behavior with Debian stretch apache 2.4.25 and Proxytunnel 1.9.  Any ideas how to get a better error message error: Socket write error. ?
