### ISSUE TITLE
Provide new Windows binaries

### ISSUE THREAD

**Issue by dagwieers** [proxytunnel/proxytunnel#15]
We do not have the infrastructure or access to Windows systems, but various users have requested new Windows build.

**Comment by dagwieers** [comment]
In order to create a Windows build, you need a recent Windows system (Windows 10) with cygwin installed. The Makefile should be modified to include -DCYGWIN in the build options:

```c
# CYGWIN
#OPTFLAGS += -DCYGWIN
```

And then simply run:
```
make
```

**Comment by Resousse** [comment]
Hi,
I compiled one with Win 7 32bits, let me know if you are interested by, and where I could send it (I'm unable to attach it to this current answer)

Thanks

**Comment by dagwieers** [comment]
@Resousse Can you share the exact process and any custom actions you had to take ? I'd like to see if we can improve the documentation. I would like to have a docs/ directory to structure the documentation we have now.

I would also like to find a solution so that we can automate the build process, and investigate how we can sign our binaries. That's the only way we can distributed trusted binaries to our users IMO. (For Linux distributions the trust lies with the distributor, but for Windows we have to provide this trust instead.

**Comment by Resousse** [comment]
I installed cygwin + dependencies (openssl, make, gcc), and I ran the 'make proxytunnel' command.
Proxytunnel arg to avoid doc generation, as I didn't have good libs installed
No big complexity hopefully :)
I didn't have to change any config file nor code file!

**Comment by dagwieers** [comment]
Thanks, so the process still works ! I'd prefer to look into the possibility of build Windows executables on Linux. If that proves impossible, we'll have to see if there's a Windows build service we can make use of.

**Comment by Resousse** [comment]
You could also create a windows VM, running on your Linux

**Comment by Lamieur** [comment]
I've tried installing Cygwin in WINE (wine-staging 1.9.8, stock Fedora) and obviously Cygwin doesn't work at all... (any exe like bash.exe complains about FAST_CWD pointer before crashing, perhaps for unrelated reason, who knows ;)).

I'm surprised no one ported this to mingw32, looks like the only dependency proxytunnel actually has on cygwin are posix sockets instead of winsock (half an hour work for project this size ;)).

So Resousse, please share the exe as I'm unable to build one myself :)

**Comment by Resousse** [comment]
Hello,

I will share it tomorrow (another computer), meanwhile, can you try without WINE? http://stackoverflow.com/questions/2033997/howto-compile-for-windows-on-linux-with-gcc-g

I never trusted WINE :)
Thanks

**Comment by Lamieur** [comment]
Not sure what you're suggesting - that thread basically says use mingw32 like a normal person - but I just explained why it doesn't compile with mingw32 (obviously I've tried that before even posting in the other issue). Is there something I'm missing?

**Comment by sigio** [comment]
http://www.maniac.nl/proxytunnel-1.9.7-cygwin.tgz should have a current build from a win7-vm with cygwin

**Comment by Resousse** [comment]
Hey,
I'm not able to see if I have the same version as sigio (my --version didn't update...)
But here are my build (with necessary dlls) : http://dl.free.fr/gfHtiLytl

Regards,

**Comment by Lamieur** [comment]
Hey, I downloaded sigio's package this morning and it works on Windows 7 and happily connects to 2016 httpd/openssl with SSLv3 disabled. Thanks a lot and see you in another 10 years! ;)

**Comment by tizzef** [comment]
Thanks for the new proxytunnel-1.9.7-cygwin, works like a charm on win 8.1. Web server is apache2.4.10 on debian jessie.
Cheers ;)

**Comment by javirg** [comment]
Thanks sigio for your build, it works flawlessly.

We're using it at work in order to connect SQL database bypassing corporate firewall, using encryption to avoid deep packet inspection issues. On the server side we use Debian Jessie with Apache.

**Comment by mcarbonneaux** [comment]
You've tryed the Microsoft build services (vsts) ?

 https://docs.microsoft.com/en-us/vsts/build-release/actions/ci-build-github

**Comment by JulAlx** [comment]
> I've just compiled it under Cygwin on Windows 10:
> 
> https://drop.me/op44P6

Thanks, man. Building with Cygwin is pain in the ...! Re-uploaded to Mega in case Drop.me goes down again.

https://mega.nz/#!i3REzKZJ!khyHUwJ4zd7HtW6QmMiEey1Fpj_dyvzY533LMfyCZW4

**Comment by javirg** [comment]
New build (March 3rd, 2020):

https://1drv.ms/u/s!As2hJalZQUH9ayA2_07IUwlH7MY?e=zxg4gO

**Comment by mcarbonneaux** [comment]
you tried with travis windows build ? they support msys2 ...

https://docs.travis-ci.com/user/reference/windows/#how-do-i-use-msys2 

sample from one of my project with csharp:
https://github.com/ZenProjects/Chromium-Web-Page-Screensaver/blob/master/.travis.yml

**Comment by mcarbonneaux** [comment]
i've made a pull request to add windows build to travis-ci : https://github.com/proxytunnel/proxytunnel/pull/47.

**Comment by shawnz** [comment]
This build works great, thank you. But, is there a way to have it use the Windows certificate store instead of a cacert.pem file?

**Comment by mcarbonneaux** [comment]
> This build works great, thank you. But, is there a way to have it use the Windows certificate store instead of a cacert.pem file?

The problem are that proxytunnel has been coded for unix system only (and they use openssl) ... 
and to build proxytunnel to window windows they use "unix -> windows" api translation "msys" ....
and for certificat they use openssl that no know about windows certificate store...

To make possible to use windows certificate store, they must be recoded to windows native api, and replace openssl api to windows crypto api...

**Comment by shawnz** [comment]
Not sure how much this helps, but I found this patch to enable wget on mingw to use the Windows certificate store. Would it be easy to add to the proxytunnel build process?

See https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-wget/openssl-windows-cert-store.patch

**Comment by mcarbonneaux** [comment]
> Not sure how much this helps, but I found this patch to enable wget on mingw to use the Windows certificate store. Would it be easy to add to the proxytunnel build process?

think can be usable in proxytunnel....
fork the repo, ans make the modification on the proxytunnel code, test it, and push pull request !
