### ISSUE TITLE
how to get the TLS session key to help wireshark decypt the traffic

### ISSUE THREAD

**Issue by moralrebuild** [proxytunnel/proxytunnel#24]
Want to take a deep look at the packets flows of proxytunnel but have no idea about how to find the TLS session keys. Without it the wireshark cannot decode the packets.  An article talks about similar effort in real broswers:

https://jimshaver.net/2015/02/11/decrypting-tls-browser-traffic-with-wireshark-the-easy-way/

**Comment by sigio** [comment]
Proxytunnel is mostly unmaintained at this time.... we will accept most pull-requests, but currently have little interest in doing improvements ourselves, since we no longer use this software.

**Comment by moralrebuild** [comment]
Thanks for your response. Are you using better alternative?

**Comment by moralrebuild** [comment]
Thanks for your response. Are you using better alternative?
