### ISSUE TITLE
proxytunnel  cannot handle password string like 'e17UR$@#b&E&'

### ISSUE THREAD

**Issue by moralrebuild** [proxytunnel/proxytunnel#25]
Once we set above string on both Apache2 and Proxytunnel sides, the proxytunnel sends wrong authentication request and fails with message "HTTP return code: 407 Proxy Authentication Required"

**Comment by sigio** [comment]
$ sign seems to cause issues.... unknown why at this time

**Comment by sigio** [comment]
Seems to work for me when providing the username and password in the passfile (-F option)
