### ISSUE TITLE
Error: HTTP/1.1 403 Certificateincident

### ISSUE THREAD

**Issue by balferreira** [proxytunnel/proxytunnel#26]
Hi.

I'm using this command and I'm getting this error:

> D:\proxytunnel-1.9.7-cygwin>proxytunnel.exe -E -p XXX.XXX.XXX.XXX:443 -d 127.0.0.1:22 -v -H "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)\n"
> Connected to XXX.XXX.XXX.XXX:443 (local proxy)
> 
> Tunneling to 127.0.0.1:22 (destination)
> Communication with local proxy:
>  -> CONNECT 127.0.0.1:22 HTTP/1.1
>  -> Host: 127.0.0.1:22
>  -> Proxy-Connection: Keep-Alive
>  -> User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)\n
>  <- HTTP/1.1 403 Certificateincident
> 
> HTTP return code: 403 Certificateincident
>  <- Content-Type: text/html
> 
>  <- Cache-Control: no-cache
> 
>  <- Content-Length: 4392
> ▒
>  <- Proxy-Connection: Keep-Alive
> 
>  <-
> .axX.a►
> 
> D:\proxytunnel-1.9.7-cygwin>

On apache default-ssf.conf, I've this configured.

> SSLCertificateFile     /etc/ssl/certs/ssl-cert-snakeoil.pem
> SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

Anyone knows what can be cause this error?
I'm trying this behind a McAfee Web Gateway, did you guys think that web gateway is blocking self-signed certificates or something similar?

Kind regards.

**Comment by sigio** [comment]
Most likely.... as the gateway has no way of knowing which certs are valid when you have a self-signed cert.
