### ISSUE TITLE
Setting up a web proxy to test Proxytunnel -r Remote Proxy feature

### ISSUE THREAD

**Issue by FlexMcMurphy** [proxytunnel/proxytunnel#30]
Hello,

Question:

How do I configure a proxy Virtualhost on Apache2 so that Proxytunnel can tunnel through it making use of its -r remote proxy feature?
Does the "local proxy" need to be a reverse proxy?
How is the "local proxy" configured to give access to any client and proxy to a remote proxy that is not hard-coded in to the Virtualhost but defined in the Proxytunnel command using the -r "remote proxy" argument.

Here is what I have got working:

I use Proxytunnel to tunnel through a forward proxy I have set up on my Apache web server to “CONNECT” to my sshd server and hence ssh over Port 80.

Here is my HTTP Apache forward proxy on port 80:

```
<VirtualHost _default_:80>
            DocumentRoot /var/www
            ServerName example.com

            ErrorLog /var/log/apache2/ssh-proxy_error_log
            CustomLog /var/log/apache2/ssh-proxy_access_log combined
            LogLevel debug

            ProxyRequests on
            ProxyVia block
            ProxyBadHeader Ignore
            AllowCONNECT 22

            <Proxy *>
               Require all denied
            </Proxy>
            <Proxy 192.168.1.124>
               Require all granted
            </Proxy>
</VirtualHost>
```

I test the connection from a windows command line with this command:

`# proxytunnel -v -p example.com:80 -d 192.168.1.124:22 -H "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)"`

And I get this output on the command line:

```
C:\Users\Me>proxytunnel -v -p example.com:80 -d 192.168.1.124:22 -H "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)"
Local proxy example.com resolves to 192.168.1.124
Connected to example.com:80 (local proxy)

Tunneling to 192.168.1.124:22 (destination)
Communication with local proxy:
-> CONNECT 192.168.1.124:22 HTTP/1.1
-> Host: 192.168.1.124:22
-> Proxy-Connection: Keep-Alive
<- HTTP/1.0 200 Connection Established

<- Proxy-agent: Apache

<-

Tunnel established.
SSH-2.0-OpenSSH_7.4p1 Raspbian-10+deb9u3
```
I have access to two Raspberry Pis set up in two different geographical locations. I am trying to understand more about how Proxytunnel works and also to learn more about web server configuration. 

How do I set up a Virtualhost on either Pi so I can make this command work:

`# proxytunnel -v -p local_proxy:port -r remote_proxy:port -d destination_hostname:port -H "User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Win32)"`

Does the Local proxy need to be a reverse proxy? How is it configured to give access to any ip address and forward to the hostname and port defined in the -r argument of the Proxytunnel command?

I guess what I'm really asking is: "How are Proxies configured so Proxytunnel can tunnel through them?"

Flex

**Comment by FlexMcMurphy** [comment]
Hello,

Just answering my own question.. maybe other amateur enthusiast types might find this info useful?

- I wanted to understand more about Proxy servers and how Proxytunnel works to tunnel through them.
- I have two Raspberry Pis... one at my house (local-proxy) and another at "a friends house" (remote-proxy).
- This is how I configured each using Apache 2.4 as a forward-proxy with basic apache2 authentication and then ran the Proxytunnel command to establish a connection through them both to my sshd server on the remote-proxy.

**This is the Virtualhost on the local-proxy:**
`# nano 000-localproxy-http.conf`

```
<VirtualHost _default_:80>

	ServerName local-proxy.com
	DocumentRoot /var/www/local-proxy

	LogLevel debug
	ErrorLog /var/www/local-proxy/logs/http-proxy-error.log
	CustomLog /var/www/local-proxy/logs/http-proxy-access.log combined

	ProxyRequests on
	ProxyBadHeader Ignore
	ProxyVia on
	AllowCONNECT 22 80
		
	# Deny all proxying by default
	<Proxy *>
		Require all denied
	</Proxy>
	# Restrict Proxying to 192.168.1.124, remote-proxy.com and whatismyip.host
	<ProxyMatch (192.168.1.124|remote-proxy.com|whatismyip.host)>
		# Authenticate access to the local-proxy.
		AuthType Basic
		AuthName "Enter Password to Access this Proxy"
		AuthBasicProvider file
		AuthUserFile "/etc/apache2/proxypwd"
		Require user localuser
	</ProxyMatch>

</VirtualHost>
```

- This allows anyone to get to this Virtualhost but they can proxy to 192.168.1.124, remote-proxy.com and whatismyip.host over Port 22 and Port 80 only and also they have to authenticate with username localuser and password.
- The LAN ip address of the local proxy is: 192.168.1.124 so with this setup I could just proxy directly to the ssh server on this Pi
- I included whatismypi.host so I can test by adding local-proxy.com on Port 80 as the proxy server in my internet browser, open that page to see the public ip address of that proxy or if I wish use the internet connection there.. restricted to http of course... so not much use!

**This is the Virtualhost on the remote proxy:**
`# nano 000-remoteproxy-http.conf`

```
<VirtualHost _default_:80>

	ServerName remote-proxy.com
	DocumentRoot /var/www/remote-proxy

	LogLevel debug
	ErrorLog /var/www/remote-proxy/logs/http-proxy-error.log
	CustomLog /var/www/remote-proxy/logs/http-proxy-access.log combined

	ProxyRequests on
	ProxyBadHeader Ignore
	ProxyVia on
	AllowCONNECT 22 80
		
	# Deny all proxying by default
	<Proxy *>
		Require all denied
	</Proxy>
	# Restrict Proxying to 192.168.0.10, local-proxy.com and whatismyip.host
	<ProxyMatch (192.168.0.10|local-proxy.com|whatismyip.host)>
		# Authenticate access to the remote-proxy.
		AuthType Basic
		AuthName "Enter Password to Access this Proxy"
		AuthBasicProvider file
		AuthUserFile "/etc/apache2/proxypwd"
		Require user remoteuser
	</ProxyMatch>

</VirtualHost>
```

The LAN ip address of the remote proxy is: 192.168.0.10

[Information here about Authentication and Authorization in Apache2](https://httpd.apache.org/docs/2.4/howto/auth.html)

**Here is the Proxytunnel command I use to hop from the local proxy to the sshd server on the remote proxy:**
- local-proxy.com and remote-proxy.com resolve to the public ip address of the local and remote Pis
- I am using the latest Proxytunnel 1.9.9 compiled from sources using Cygwin (32-bit) to run from a Windows 7 command line.
- The local and remote username and passwords could instead go in a file called "credentials" that proxytunnel will read from the parameter: -F credentials

```
> proxytunnel -v -P localuser:localpwd -R remoteuser:remotepwd -p local-proxy.com:80 -r remote-proxy.com:80 -d 192.168.0.10:22
Connected to local-proxy.com:80 (local proxy)

Tunneling to remote-proxy.com:80 (remote proxy)
Communication with local proxy:
 -> CONNECT remote-proxy.com:80 HTTP/1.1
 -> Host: remote-proxy.com:80
 -> Proxy-Authorization: Basic YmVhZ6xlOoRlc3PyMg+=
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.0 200 Connection Established

 <- Proxy-agent: Apache

 <-


Tunneling to 192.168.0.10:22 (destination)
Communication with remote proxy:
 -> CONNECT 192.168.0.10:22 HTTP/1.1
 -> Host: 192.168.0.10:22
 -> Proxy-Authorization: Basic ZOFyk2liOnElc3M=
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.0 200 Connection Established

 <- Proxy-agent: Apache/2.4.25 (Raspbian)

 <-


Tunnel established.
SSH-2.0-OpenSSH_7.4p1 Raspbian-10+deb9u3
Tunnel closed.
```

**Here are the http-proxy-access.logs from both Pis after running the above command:**

- 192.168.1.101 is the local lan ip address of my Win7 laptop

`-- /var/www/local-proxy/logs/http-proxy-access.log`
```
192.168.1.101 - localuser [28/May/2018:02:18:57 +0100] "CONNECT remote-proxy.com:80 HTTP/1.1" 200 179 "-" "-"
```
`-- /var/www/remote-proxy/logs/http-proxy-access.log`
```
[Public.IP.of.remote-proxy] - remoteuser [28/May/2018:02:18:59 +0100] "CONNECT 192.168.0.10:22 HTTP/1.1" 200 119 "-" "-"
```

**Proxytunnel can be used in four different ways with this setup:**
```
-- Proxy to ssh server on local-proxy
# proxytunnel -v -P localuser:localpwd -p local-proxy.com:80 -d 192.168.1.124:22

-- Proxy to ssh server on remote-proxy (in this scenario Proxytunnel sees remote-proxy as the local proxy)
# proxytunnel -v -P remoteuser:remotepwd -p remote-proxy.com:80 -d 192.168.0.10:22

-- Proxy to ssh server on remote-proxy via local-proxy
# proxytunnel -v -P localuser:localpwd -R remoteuser:remotepwd -p local-proxy.com:80 -r remote-proxy.com:80 -d 192.168.0.10:22

-- Proxy to ssh server on local-proxy via remote-proxy (in this scenario Proxytunnel sees remote-proxy as the local proxy)
# proxytunnel -v -P remoteuser:remotepwd -R localuser:localpwd -p remote-proxy.com:80 -r local-proxy.com:80 -d 192.168.1.124:22
```

**Note:**

- I found that Proxytunnel doesn't do SNI properly over http.
- Whatever domain name I used in the Proxytunnel command it always just went to the default virtualhost. so this must contain the forward proxy instructions.
- Enforce a virtualhost as the default by naming it with a bunch of preceeding zeros so it will come first in a directory listing... test with # ls -1 (number one, not letter l).
- Check what Virtualhosts are enabled and which is the default with # apache2ctl -S

**Suggestion:**
I think Proxytunnel 1.9.9 does proper SNI under https, would be great if someone got Proxytunnel SNI working under http as well?!

Feedback and corrections glady welcomed!

Flex

**Comment by sigio** [comment]
You can probably add a -H "Host: some-hostname" option on the
commandline.

That's all that SNI is/does... and proxytunnel supports -H for extra
headers.
