### ISSUE TITLE
Proxytunnel does not match -p <hostname> to ServerName in Apache Virtualhost over HTTP

### ISSUE THREAD

**Issue by FlexMcMurphy** [proxytunnel/proxytunnel#31]
Hello,

From my testing Proxytunnel 1.9.9 does not handle SNI correctly when proxying to a HTTP forward proxy.. whatever hostname is provided for the local proxy apache processes the default Virtualhost.

At the end of Issue #30 it was suggested to use the Proxytunnel -H "host: hostname" argument to supply a hostname so that the webserver will direct processing to the correct Virtualhost server side. My testing shows that this is not the case.

**My Virtualhost that defines a http Proxy is like this:**

```
<VirtualHost _default_:80>
	ServerName api.example.com
	DocumentRoot /var/www/html

	LogLevel debug
	ErrorLog /var/www/myproxy/logs/http-proxy-error.log
	CustomLog /var/www/myproxy/logs/http-proxy-access.log combined
..
..
</VirtualHost>
```
**I also have another Virtualhost that defines a simple website on Port 80 like this:**

```
<VirtualHost _default_:80>
	
	ServerName example.com
	ServerAlias www.example.com
	
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/appleloli

	ErrorLog /var/www/mysite/logs/http-error.log
	CustomLog /var/www/mysite/logs/http-access.log combined

</VirtualHost>
```

If I try this Proxytunnel command:

`proxytunnel -v -P flex:pwd -p example.com:80 -d 192.168.0.10:22`

You would think it shouldn't work because I have a ServerName: example.com in a Virtualhost that defines no Proxy. However I do get the OpenSSH banner.

Nothing is logged in the http-access.log or http-error.log

This is what is logged in http-proxy-access.log
`my.public.ip.addr - flex [28/May/2018:19:04:09 +0100] "CONNECT 192.168.0.10:22 HTTP/1.1" 200 119 "-" "-"`

This is what is logged in http-proxy-error.log
```
[Mon May 28 19:04:09.638046 2018] [core:debug] [pid 23337:tid 3018847280] vhost.c(1172): [client my.public.ip.addr:53606] AH02417: Replacing host header 'example.com' with host '192.168.0.10:22' given in the request uri
[Mon May 28 19:04:09.638746 2018] [authz_core:debug] [pid 23337:tid 3018847280] mod_authz_core.c(809): [client my.public.ip.addr:53606] AH01626: authorization result of Require user flex: denied (no authenticated user yet)
[Mon May 28 19:04:09.638907 2018] [authz_core:debug] [pid 23337:tid 3018847280] mod_authz_core.c(809): [client my.public.ip.addr:53606] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Mon May 28 19:04:09.642679 2018] [authz_core:debug] [pid 23337:tid 3018847280] mod_authz_core.c(809): [client my.public.ip.addr:53606] AH01626: authorization result of Require user flex: granted
[Mon May 28 19:04:09.642899 2018] [authz_core:debug] [pid 23337:tid 3018847280] mod_authz_core.c(809): [client my.public.ip.addr:53606] AH01626: authorization result of <RequireAny>: granted
[Mon May 28 19:04:09.643503 2018] [proxy:debug] [pid 23337:tid 3018847280] mod_proxy.c(1228): [client my.public.ip.addr:53606] AH01143: Running scheme 192.168.0.10 handler (attempt 0)
[Mon May 28 19:04:09.643678 2018] [proxy_connect:debug] [pid 23337:tid 3018847280] mod_proxy_connect.c(201): [client my.public.ip.addr:53606] AH01019: connecting 192.168.0.10:22 to 192.168.0.10:22
```

It looks like Apache is seeing the correct hostname header - example.com - without needing to use the -H "host: hostname" argument at all. Yet the "wrong" Virtualhost is selected by Apache.

**I tried the suggestion to use the Proxytunnel -H "host: hostname" argument like this:**

`proxytunnel -v -P flex:pwd -p example.com:80 -d 192.168.0.10:22 -H "Host: api.example.com"`

What should be the expected result?

If SNI works properly with Proxytunnel and since I have a Virtualhost (that does not define any proxy) with ServerName: example.com it should match with that and I shouldn't get any connection to my sshd server. 

However I DO did get a connection to my sshd server. Why? Maybe the suggestion to add a host name using the header -H option worked out? I added the -H "Host: api.example.com" argument so maybe this is what apache sees and therefore selects the Proxy Virtualhost that has ServerName api.example.com in it?

I don't think this is what is happening behind the scenes:

This is logged to http-proxy-access.log
`my.public.ip.addr - flex [28/May/2018:18:44:43 +0100] "CONNECT 192.168.0.10:22 HTTP/1.1" 200 119 "-" "-"`
This is logged to http-proxy-error.log
```
[Mon May 28 18:44:43.325731 2018] [core:debug] [pid 23338:tid 2993681456] vhost.c(1172): [client my.public.ip.addr:53516] AH02417: Replacing host header 'example.com, api.example.com' with host '192.168.0.10:22' given in the request uri
[Mon May 28 18:44:43.326293 2018] [authz_core:debug] [pid 23338:tid 2993681456] mod_authz_core.c(809): [client my.public.ip.addr:53516] AH01626: authorization result of Require user flex: denied (no authenticated user yet)
[Mon May 28 18:44:43.326453 2018] [authz_core:debug] [pid 23338:tid 2993681456] mod_authz_core.c(809): [client my.public.ip.addr:53516] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Mon May 28 18:44:43.329849 2018] [authz_core:debug] [pid 23338:tid 2993681456] mod_authz_core.c(809): [client my.public.ip.addr:53516] AH01626: authorization result of Require user flex: granted
[Mon May 28 18:44:43.330024 2018] [authz_core:debug] [pid 23338:tid 2993681456] mod_authz_core.c(809): [client my.public.ip.addr:53516] AH01626: authorization result of <RequireAny>: granted
[Mon May 28 18:44:43.330266 2018] [proxy:debug] [pid 23338:tid 2993681456] mod_proxy.c(1228): [client my.public.ip.addr:53516] AH01143: Running scheme 192.168.0.10 handler (attempt 0)
[Mon May 28 18:44:43.330429 2018] [proxy_connect:debug] [pid 23338:tid 2993681456] mod_proxy_connect.c(201): [client my.public.ip.addr:53516] AH01019: connecting 192.168.0.10:22 to 192.168.0.10:22
```
It seems that adding the -H "Host: api.example.com" argument to Proxytunnel just concatenates the local proxy host name and the host name provided in the additional header argument and this combination is what apache sees as the hostname.

In the first test above Apache2 must be seeing: "example.com" as the host header and in the second test apache sees: "example.com, api.example.com" as the host header... in both cases the default virtualhost is selected.

If I don't define the proxy in the default virtualhost then it would never work.

I haven't fully tested but recently a fix was merged https://github.com/proxytunnel/proxytunnel/pull/23 that fixes SNI handling. It may be that this works with https only?

Any comments or corrections gratefully received.

Flex

**Comment by sigio** [comment]
Is still relevant, could you test with a recent build ?
