### ISSUE TITLE
MaxKeepAliveRequests in apache2 is not respected by proxytunnel

### ISSUE THREAD

**Issue by moralrebuild** [proxytunnel/proxytunnel#34]
I want to make proxytunnel re-establishes connection for a couple of hours in order to avoid long running http connection. The reason is my company's firewall detects the suspected long running connections and blacklist the client nodes. 

B.T.W. It looks like this project has no active maintainers any more. It's really pity for such a great software.

**Comment by sigio** [comment]
autossh will re-trigger your ssh command, so it doesn't have to be implemented in proxytunnel.
And you can also use the ClientKeepAlive's in ssh itself.
