### ISSUE TITLE
Missing Error Check in function SSL_connect()

### ISSUE THREAD

**Issue by lc3412** [proxytunnel/proxytunnel#36]
Hi,
Function SSL_connect() returns the value of 0 and less than 0 are both on error. However , the return value of function SSL_connect() is not checked . See the following code:

line: 314
https://github.com/proxytunnel/proxytunnel/blob/f7831a292f7182dc20e5dbd11a90c18474b6077b/ptstream.c#L288-L314

==================================================================================

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/apps folder

line: 376, 377
ref: https://github.com/openssl/openssl/blob/1362190b1b786a87378e55e9a1c20c46b6b6a286/apps/s_time.c#L376-L387

```c
line 376:    i = SSL_connect(serverCon);
line 377:    if (i <= 0) {
line 378:        BIO_printf(bio_err, "ERROR\n");
line 379:        if (verify_args.error != X509_V_OK)
line 380:            BIO_printf(bio_err, "verify error:%s\n",
line 381:                               X509_verify_cert_error_string(verify_args.error));
line 382:        else
line 383:            ERR_print_errors(bio_err);
line 384:        if (scon == NULL)
line 385:             SSL_free(serverCon);
line 386:        return NULL;
line 387:    }
```

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by sigio** [comment]
fixed in ab33f01fbd21c7527da7e39d0d6b883bcbc82204
