### ISSUE TITLE
Missing Error Check in function SSL_new() 

### ISSUE THREAD

**Issue by lc3412** [proxytunnel/proxytunnel#37]
Hi,
Function SSL_new() returns a pointer to an SSL object on success or NULL on error. However, the function SSL_new() didn't check the return value is NULL or not, before passing the return value as an argument to both the function SSL_set_rfd() and SSL_set_wfd(). See the following details.

https://github.com/proxytunnel/proxytunnel/blob/f7831a292f7182dc20e5dbd11a90c18474b6077b/ptstream.c#L288-L291

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by sigio** [comment]
fixed in ab33f01fbd21c7527da7e39d0d6b883bcbc82204
