### ISSUE TITLE
Use proxytunnel with Openvpn without ssh

### ISSUE THREAD

**Issue by mancioshell** [proxytunnel/proxytunnel#39]
Hi All,
thanks for your great work!

I have used proxytunnel to established a tunnel form a local http proxy and remote http proxy to connect to an openvpn server. Command is something like that:
`proxytunnel -v -p my-local-proxy:3128 -R proxy-username:proxy-password -r my-remote-proxy:80 -d my-remote-openvpn-server:444`

Tunnel is established properly, but now i would like to use an openvpn-client to connect to openvpn-server through this tunnel. I have tried to use -a option to run proxytunnel as standalone daemon, and i have used socks-proxy configuration options on openvpn, but unfortunately with no success.

Any advice to accomplish this task without establish an ssh tunnel?

**Comment by sigio** [comment]
SSH portforwarding ?
