### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by mageta** [proxytunnel/proxytunnel#40]
It would sure be nice if you could put out a new release tag at some point. Linux Distributions don't pick up any new version of proxytunnel, unless that exists (e.g.: fedora and gentoo are on 1.9.1 or even 1.9.0), and so we miss some nice new stuff like SNI support for HTTPS, TLS improvements and some fixes.

**Comment by FlexMcMurphy** [comment]
I also wish this useful program was being more actively supported and maintained.

I compiled Proxytunnel myself from sources one year ago and it hasn't changed from then. I managed to compile it on linux Raspbian OS and also under Cygwin to make a binary that runs on Windows. Let me know if you need help and I can tell you exactly what I did.

SNI support is very useful.

Flex

**Comment by pedrohdz** [comment]
Would be nice so that _brew_ and _macports_ could pick up the updates as well.

Please bump the version number.

**Comment by anthraxx** [comment]
@sigio can we get a new git release tag? that would be awesome, so we can ship the new version to our distro users.

**Comment by sigio** [comment]
v1.10.20210128 tag should just be created ;)
