### ISSUE TITLE
Update sourceforge page to link to github

### ISSUE THREAD

**Issue by kpcyrd** [proxytunnel/proxytunnel#42]
Hello,

proxytunnel was flagged as outdated in Arch Linux and pointed to this repository, but I can't find anything on the old sourceforge page that links to this repository to verify authenticity.

Can you add a link or a news post on the old page that the repository has been moved here officially?

**Comment by sigio** [comment]
The entire project is mostly unmaintained. The github repo is the official source at this time.

**Comment by sigio** [comment]
https://sourceforge.net/projects/proxytunnel/ has a link to github now.... I have no idea how to update the webpages on proxytunnel.sf.net anymore.
