### ISSUE TITLE
Missing retries when writing to socket

### ISSUE THREAD

**Issue by 68420948** [proxytunnel/proxytunnel#45]
Back in 2013 it had been detected at Debian [1] that proxytunnel will fail if the call to send() does not return the requested number of bytes to be written.

Please consider to apply the patch available from Debian [2] to fix this in your source.

Regards,
Sven

[1] https://bugs.debian.org/717771
[2] https://salsa.debian.org/pkg-security-team/proxytunnel/-/blob/debian/master/debian/patches/003_socket_write_loop.patch

**Comment by sigio** [comment]
commit cb336cab716beb62b8dbda0a9235798e2d81e4f6
Author: Mark Janssen -- Sig-I/O Automatisering <mark@sig-io.nl>
Date:   Thu May 7 17:02:39 2020 +0200

    Apply debian patch 003_socket_write_loop.patch
