### ISSUE TITLE
Optionally accept alternative default CA file and/or directory path at compile time

### ISSUE THREAD

**Issue by deFractal** [proxytunnel/proxytunnel#53]
Currently, `proxytunnel` looks by default for a CA certificate file in `/etc/ssl/certs`, but on current versions of macOS, that directory is always empty. This has the effect that, to use `proxytunnel` on macOS (as shipped with Homebrew, for example), one must _always_ specify a path using `--cacert` at runtime. To address this, I've drafted a small patch to allow specifying a different default at compile time. 

If a PR with a patch to this effect would be welcome, I'd be glad to open one based on [my test fork, here](https://github.com/deFractal/proxytunnel/pull/1). I've compiled this and verified it works on macOS Catalina as a drop-in replacement for the current version `proxytunnel` provided through Homebrew. 

For example, I can use the resulting binary for an SSH/HTTPS tunnel, …</summary> after uncommenting the existing `DARWIN` and new `DARWIN, continued…` options in the `Makefile` and compiling. This lets me replace lines in scripts which currently look like: 

```
proxytunnel --quiet --encrypt-proxy --cacert="$(/usr/local/opt/openssl/bin/openssl version -d | cut -d'"' -f2)/cacert.pem" --proxy=some-server.invalid:443 --dest=127.0.0.1:22
```
with:

```
~/Documents/GitHub/proxytunnel/proxytunnel --quiet --encrypt-proxy --proxy=some-server.invalid:443 --dest=127.0.0.1:22
```
(Of course, the explicit binary path would no longer be needed in the final version.) 

Feedback welcome. Thoughts?

**Comment by sigio** [comment]
Patches / pull-requests are welcome.... as long as they don't break windows + linux builds ;)

**Comment by deFractal** [comment]
Move to PR #54.
