### ISSUE TITLE
Patch: SSL_set_tlsext_host_name() > 0 indicates a problem. Not < 0.

### ISSUE THREAD

**Issue by ZjYwMj** [proxytunnel/proxytunnel#57]
Consider [lines 343-347 of ptstream.c](https://github.com/proxytunnel/proxytunnel/blob/e2a214d942c46268cf427341eacb296428079026/ptstream.c#L343-L347):
```
   res = SSL_set_tlsext_host_name(ssl, peer_host);
   if (res < 0) {
       message( "TLS SNI error, giving up: SSL_set_tlsext_host_name returned error message:\n %u\n", res );
       exit( 1 );
   }
```
But [man SSL_set_tlsext_host_name](https://manpages.debian.org/bullseye/libssl-doc/SSL_set_tlsext_host_name.3ssl.en.html) shows exit codes of the form `SSL_TLSEXT_ERR_*`. By [openssl/tls1.h](https://github.com/openssl/openssl/blob/7e5e91176b770a68bdaf73a5c647f1fc0d7f2900/include/openssl/tls1.h#L298-L301), these have values >= 0.
Following the [openssl-bio-fetch.tar.gz](https://wiki.openssl.org/images/d/dc/Openssl-bio-fetch.tar.gz) example from the [openssl wiki](https://wiki.openssl.org/index.php/SSL/TLS_Client), I suggest:
```
--- a/ptstream.h	2021-01-28 22:12:52.000000000 +0000
+++ b/ptstream.h	2022-05-26 13:29:54.199452530 +0000
@@ -21,6 +21,7 @@
 
 #ifdef USE_SSL
 #include <openssl/crypto.h>
+#include <openssl/err.h>
 #include <openssl/x509.h>
 #include <openssl/pem.h>
 #include <openssl/ssl.h>
```
and
```
--- a/ptstream.c	2021-01-28 22:12:52.000000000 +0000
+++ b/ptstream.c	2022-05-26 17:32:04.192694338 +0000
@@ -333,8 +333,10 @@
 		message( "Set SNI hostname to %s\n", peer_host);
 	}
 	res = SSL_set_tlsext_host_name(ssl, peer_host);
-	if (res < 0) {
-		message( "TLS SNI error, giving up: SSL_set_tlsext_host_name returned error message:\n  %u\n", res );
+	if (res != SSL_TLSEXT_ERR_OK) {
+		unsigned long ssl_err = (res == SSL_TLSEXT_ERR_ALERT_WARNING ? SSL_TLSEXT_ERR_ALERT_WARNING : ERR_get_error());
+		message( "SSL_set_tlsext_host_name returned: %lu (0x%lx). "
+		         "TLS SNI error, giving up\n", ssl_err, ssl_err );
 		exit( 1 );
 	}

```
As far as I can tell, there are no other occurences of `SSL_set_tlsext_host_name()` in the code.

**Comment by o1chris** [comment]
This change does not work when compiled/linked against openssl 1.1 or 3. SSL_set_tlsext_hostname() returns 1 on success. SSL_TLSEXT_ERR_OK is defined as 0 0

> # define SSL_TLSEXT_ERR_OK 0

https://www.openssl.org/docs/man1.1.1/man3/SSL_set_tlsext_host_name.html
https://manpages.debian.org/bullseye/libssl-doc/SSL_set_tlsext_host_name.3ssl.en.html
> SSL_set_tlsext_host_name() returns 1 on success, 0 in case of error.

**Comment by ZjYwMj** [comment]
> This change does not work when compiled/linked against openssl 1.1 or 3. SSL_set_tlsext_hostname() returns 1 on success. SSL_TLSEXT_ERR_OK is defined as 0

As evident from the URLs below, it is a typo. There is a missing underscore character: ```SSL_set_tlsext_host_name()```

> 
> `> # define SSL_TLSEXT_ERR_OK 0`
> 
> https://www.openssl.org/docs/man1.1.1/man3/SSL_set_tlsext_host_name.html https://manpages.debian.org/bullseye/libssl-doc/SSL_set_tlsext_host_name.3ssl.en.html
> 
> > SSL_set_tlsext_host_name() returns 1 on success, 0 in case of error.

My mistake. But in any case, the block 
```
   res = SSL_set_tlsext_host_name(ssl, peer_host);
   if (res < 0) {
       message( "TLS SNI error, giving up: SSL_set_tlsext_host_name returned error message:\n %u\n", res );
       exit( 1 );
   }
```
is wrong, isn't it?

**Comment by NickHibma** [comment]
From the OpenSSL 1.1.1 man page [1]: "SSL_set_tlsext_host_name() returns 1 on success, 0 in case of error.", so it should be:
```
res = SSL_set_tlsext_host_name(ssl, peer_host);
if ( res != 1 ) {
   message( "SSL_set_tlsext_host_name(%s) failed. "
            "TLS SNI error, giving up\n", peer_host);
   goto fail;
}
```

This includes a change of `exit(1)` to `goto fail` to match the surrounding code.

As it is SSL based connections will not work,

[1] https://www.openssl.org/docs/man1.1.1/man3/SSL_set_tlsext_host_name.html

**Comment by NickHibma** [comment]
Also: Checking for this error return could also be simply skipped, as this function can only fail when bogus input is provided. See also the example provided by IBM [1]. it does not check the return value.

[1] https://www.ibm.com/docs/en/ztpf/2022?topic=examples-client-application
