### ISSUE TITLE
Patch: parse_cmdline: could not find your proxy hostname/ip does not refer to a dns resolution issue

### ISSUE THREAD

**Issue by ZjYwMj** [proxytunnel/proxytunnel#58]
Currently,
```
$ proxytunnel -p proxy.server1.tld -d www.server2.tld:port
```
results in the following error message:
```
parse_cmdline: could not find your proxy hostname/ip (proxy.server1.tld)
```
IMHO, such an error message can be associated by the user with a dns resolution issue. Which is misleading here.
The patch follows the manual page to explicitly mentions the required specification of the proxy port too. And explicitly mentions an expected pattern.
```
--- a/cmdline.c	2022-05-26 19:29:32.621516175 +0000
+++ b/cmdline.c	2022-05-27 21:20:21.420538767 +0000
@@ -581,7 +581,7 @@
 			args_info->proxyhost_given = 1;
 			args_info->proxyport_given = 1;
 		} else {
-			message( "parse_cmdline: could not find your proxy hostname/ip (%s)\n", args_info->proxy_arg );
+			message( "parse_cmdline: specified proxy hostname/ip:port (%s) does not fit expected pattern\n", args_info->proxy_arg );
 			missing_required_options++;
 		}
 	}
```
It could be a better approach would be to have the code more ditsinctly handle the proxy hostname/ip and the proxy port. Something along the lines of
```
    parse the proxy hostname/ip
    if there is a problem, output an error message
    parse the proxy port
    if there is a problem, output a different error message
```
But I have no time for that.
I have not looked for the error messages when parsing the -r remote, 2nd, proxy. Or the -d destination host. It could be these messages are similar to the message above.

**Comment by sigio** [comment]
Proxytunnel has mostly been unmaintained for 10+ years.... and I haven't used it myself in as many years. I'll merge pull-requests, but that's about the amount of effort i'm willing to put into this ;)
