### ISSUE TITLE
"Broken pipe" error when pressing Ctrl+C too fast or when Ctrl+C with slow connection

### ISSUE THREAD

**Issue by FrostKiwi** [proxytunnel/proxytunnel#61]
First of all big thanks to this project. Incredibly easy to use and saved me from having to setup a whole VPN just to SSH into my machine.

I have an SSH connection to a machine with a fair bit of latency due to being on the other side of the planet. Various situation cause `client_loop: send disconnect: Broken pipe` to be emitted and being thrown out of the SSH session.

The first once is pressing Ctrl+C twice in quick succession. When the prompt has not returned after Ctrl+C was emitted, then the above error occurs. Even when it's almost instant, with no process running.
Another such occasion is a hanging process, which is very annoying. I'm not 100% sure what the exact parameters are to reproduce this one, but if a process, let's say CURL, waits for a timeout or something and you press Ctrl+C, you should return to the remote system's prompt. But instead you get completely booted out of the whole SSH Session with the above error.

I guess this is similar to a 'Window not responding' under Windows, but with proxytunnel it results in an instant killing of the connection, even though just waiting 100ms or so would result in everything being ok...

**Comment by sigio** [comment]
This project is mostly unmaintained for 10 years... we only apply submitted patches.
Don't expect any new development/fixes. I never use the software myself anymore.

**Comment by FrostKiwi** [comment]
> This project is mostly unmaintained for 10 years... we only apply submitted patches. Don't expect any new development/fixes. I never use the software myself anymore.

Fully aware, just wanted to note it down, in case someone comes across it.

10years ago, yet still runs rock solid for me. Clearly some fine wine Repo^^

**Comment by FrostKiwi** [comment]
Does not seem to be an issue with `1.12.0` anymore.
