### ISSUE TITLE
Could you please publish a list of options for https proxy in the README?

### ISSUE THREAD

**Issue by yurivict** [proxytunnel/proxytunnel#65]
nginx, for example, doesn't support the CONNECT command.

What are the most basic choices of https proxies on linux that would work with proxytunnel?

**Comment by FlexMcMurphy** [comment]
Hello,

According to [this RFC](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.6), most origin servers do not implement CONNECT. I have used Apache2 with proxytunnel but Apache2 does not support the CONNECT method by default I had to [install additional modules](https://httpd.apache.org/docs/2.4/mod/mod_proxy_connect.html): mod_proxy and mod_proxy_connect.

I think [nginx does not have official support for CONNECT](https://serverfault.com/a/1090581/190972) but there are [third party modules for nginx](https://github.com/chobits/ngx_http_proxy_connect_module) freely available on GitHub.

I don't know about other web servers/proxies. Google might help.

Flex

**Comment by yurivict** [comment]
This nginx module requires whole nginx server patch and rebuild, which is quite intrusive.

I was looking for something more light-weight, maybe in Go.
Unfortunately googling doesn't find anything like this.

**Comment by yurivict** [comment]
I confirm that nginx with the third-party module http_proxy_connect works.

Thank you.
