### ISSUE TITLE
Connection fails through nginx: 400 Bad Request

### ISSUE THREAD

**Issue by yurivict** [proxytunnel/proxytunnel#66]
I am running nginx with the third party http_proxy_connect module on FreeBSD.
The ssh client setup is exactly like in the README:
```
host foo
        ProxyCommand /usr/local/bin/proxytunnel -p {host-name}:8080 -d localhost:443
```

nginx config is exactly like described in the README.

The session fails:
```
$ ssh foo
Via xx.xx.xx:8080 -> localhost:443
HTTP return code: 400 Bad Request
Fssh_kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

nginx writes this line into access.log:
```
192.168.5.1 - - [03/May/2023:23:13:12 -0700] "CONNECT localhost:443 HTTP/1.1" 400 255 "-" "-"
```

"400 Bad Request" is returned.

While looking at the kernel log on the client I see that it first connects through https, then it closes the socket, and then it connects again and sends the CONNECT command through http. Why does it need to connect through http?

When browser connects to the same host via https it sees the default nginx page saying that connection is successful.

What might be wrong?

**Comment by yurivict** [comment]
The problem was distilled into this PR: https://github.com/proxytunnel/proxytunnel/pull/67

**Comment by FrostKiwi** [comment]
Could you share your NGINX config?
