### ISSUE TITLE
`Tunnel established` message, even though it wasn't

### ISSUE THREAD

**Issue by FrostKiwi** [proxytunnel/proxytunnel#78]
This is regarding a misconfiguration and proxytunnel telling about a tunnel being established, even though no such thing happened.

I'm packaging my SSH connections in HTTPS to break through packet inspecting firewalls. My main HTTP server is Caddy, [but it doesn't support CONNECT](https://caddy.community/t/how-to-setup-ssh-over-https-with-caddy/21520/2).

<details><summary>NixOS Apache Setup</summary>

```nix
httpd = {
  enable = true;
  virtualHosts.localhost = {
    listen = [
      {
        ip = "*";
        port = <redacted>;
        ssl = false;
      }
    ];
    extraConfig = ''
      LoadModule proxy_module modules/mod_proxy.so
      LoadModule proxy_connect_module modules/mod_proxy_connect.so
      LoadModule proxy_http_module modules/mod_proxy_http.so
      ProxyVia block
      ProxyRequests on
      AllowConnect 22
      <Proxy *>
        # Deny all proxying by default ...
        Require all denied
      </Proxy>
      <Proxy 127.0.0.1>
        # Now allow proxying through localhost only
        Require all granted
      </Proxy>
    '';
...
  };
};
```

</details>

when connecting to apache, proxytunnel works and correctly translates the HTTP -> SSH Jump for HTTP and HTTPS. Here is what the connection looks like with HTTP when inspecting the tunnel with `-v`
## HTTP
```
Connected to <redacted> (local proxy)

Tunneling to <redacted> (remote proxy)
Communication with local proxy:
 -> CONNECT <redacted> HTTP/1.1
 -> Host: <redacted>
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.1 200 Connection established

 <-


Tunneling to 127.0.0.1:22 (destination)
Communication with remote proxy:
 -> CONNECT 127.0.0.1:22 HTTP/1.1
 -> Host: 127.0.0.1:22
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.0 200 Connection Established

 <- Proxy-agent: Apache/2.4.58 (Unix) OpenSSL/3.0.12

 <-


Tunnel established.
SSH-2.0-OpenSSH_9.6
```
The issue arises when passing this connection via reverse proxy through caddy to make it available on the same IP, same 443 port as other services but one specific subdomain. The next sentence is conjecture: Since Caddy doesn't handle CONNECT, it throws back a simple HTTP response, breaking proxytunnel, which proxytunnel doesn't understand as a broken state:
```
Connected to <redacted> (local proxy)

Tunneling to <redacted>:443 (remote proxy)
Communication with local proxy:
 -> CONNECT <redacted>:443 HTTP/1.1
 -> Host: <redacted>:443
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.1 200 Connection established

 <-

Set SNI hostname to <redacted>

Tunneling to 127.0.0.1:22 (destination)
Communication with remote proxy:
 -> CONNECT 127.0.0.1:22 HTTP/1.1
 -> Host: 127.0.0.1:22
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.1 200 OK

 <- Alt-Svc: h3=":443"; ma=2592000
0
 <- Server: Caddy

 <- Date: Fri, 12 Jan 2024 02:07:47 GMT

 <- Content-Length: 0

 <-


Tunnel established.
```
Note the missing `SSH-2.0-OpenSSH_9.6` at the end. Passing this through SSH results in `kex_exchange_identification: Connection closed by remote host`
```
debug1: kex_exchange_identification: banner line 0: HTTP/1.1 400 Bad Request
debug1: kex_exchange_identification: banner line 1: Content-Type: text/plain; charset=utf-8
debug1: kex_exchange_identification: banner line 2: Connection: close
debug1: kex_exchange_identification: banner line 3:
kex_exchange_identification: Connection closed by remote host
```

So proxytunnel doesn't understand the broken state and proceeds to tell about an established Tunnel, even though it is not.

**Comment by 68420948** [comment]
Caddy should not return a 200 response if does not know how to handle a CONNECT request, a 501 response would be appropriate. Please raise a ticket with Caddy.

**Comment by FrostKiwi** [comment]
> Caddy should not return a 200 response if does not know how to handle a CONNECT request, a 501 response would be appropriate. Please raise a ticket with Caddy.

Good to know it's a caddy thing. Indeed that is a Caddy feature. Opening a non-existing page gives a blank browser screen by default.
