### ISSUE TITLE
No support for proxy with username and password

### ISSUE THREAD

**Issue by pmithrandir** [proxytunnel/proxytunnel#8]
Hello,

Most software today understand the following http_proxy environment variable : 
http://username:password@host:port/

Proxytunnel doesn't, which make it incompatible with this variable.
Worst, the format is not even recognize to extract only the host and port, so we cannot just add the proxyuser and proxypassword environment variable to make it work.

On this file https://github.com/proxytunnel/proxytunnel/blob/master/cmdline.c#L490
We should juste change the logic to parse it this way : 

```
if contains @
cut the string in 2 part
part1 = user[:password]
part2 = host[:port]
else
use current code
endif
```

And to apply the same rule that you are using in your code.

Do you think it will be possible ?
Do you need me to do the code and do a pull request ?
I'm not familiar with c++ at all, so I might not be very efficient, neither without bugs...

Best regards,
Pierre

**Comment by sigio** [comment]
Think this should be covered by the various methods proxytunnel implements:
 -F, --passfile=STRING      File with credentials for proxy authentication
 -P, --proxyauth=STRING     Proxy auth credentials user:pass combination
 -R, --remproxyauth=STRING  Remote proxy auth credentials user:pass combination
