### ISSUE TITLE
NGINX config?

### ISSUE THREAD

**Issue by FrostKiwi** [proxytunnel/proxytunnel#81]
I connect to SSH over HTTPS.
Following http://dag.wiee.rs/howto/ssh-http-tunneling/ I implemented this on my server using Apache. Works great! Now I wish to transfer that config to nginx using module https://github.com/chobits/ngx_http_proxy_connect_module. Is this possible? What am I doing wrong?

For simplicity, the following example shows the non encrypted configuration. The configuration is from my NixOS config.
```nix
httpd = {
  enable = true;
  virtualHosts."localhost:21343" = {
    listen = [
      {
        ip = "*";
        port = 21343;
        ssl = false;
      }
    ];

    extraConfig = ''
      LoadModule proxy_module modules/mod_proxy.so
      LoadModule proxy_connect_module modules/mod_proxy_connect.so
      LoadModule proxy_http_module modules/mod_proxy_http.so
      ProxyRequests on
      AllowConnect 22
      <Proxy *>
        # Deny all proxying by default ...
        Require all denied
      </Proxy>
      <Proxy 127.0.0.1>
        # Now allow proxying through localhost only
        Require all granted
      </Proxy>
  '';
  };
```
This results in a successful connection as tested by `proxytunnel.exe -v` (Here the connection goes through an additional local proxy `127.0.0.1:54450`, which is not relevant to this issue)
```console
proxytunnel.exe -v -q -p 127.0.0.1:54450 -r example.org:21343 -d 127.0.0.1:22
Tunneling to example.org:21343 (remote proxy)
Communication with local proxy:
 -> CONNECT example.org:21343 HTTP/1.1
 -> Host: example.org:21343
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.1 200 Connection established

 <-

Tunneling to 127.0.0.1:22 (destination)
Communication with remote proxy:
 -> CONNECT 127.0.0.1:22 HTTP/1.1
 -> Host: 127.0.0.1:22
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.0 200 Connection Established

 <- Proxy-agent: Apache/2.4.59 (Unix)

 <-

Tunnel established.
SSH-2.0-OpenSSH_9.6
```
Now I configure the same with nginx, because nginx is my main HTTP server and I wish to do this over a subdomain, instead of another random non-standard port.
```nix
nginx = {
  enable = true;
  recommendedProxySettings = true;
  recommendedTlsSettings = true;
  recommendedGzipSettings = true;
  recommendedBrotliSettings = true;
  recommendedZstdSettings = true;
  recommendedOptimisation = true;

  additionalModules = [ pkgs.nginxModules.http_proxy_connect_module_v24 ];

  virtualHosts = {
    "example.org" =  {
      root = "/var/www/example.org";
      enableACME = true;
      forceSSL = true;
    };

    "ssh.example.org" =  {
      extraConfig = ''
        proxy_connect;
        proxy_connect_allow  all; # For testing set to all
        proxy_connect_address 127.0.0.1:22;
      '';
    };
  };
};
```
Connecting to this results in a rejection however.
```console
proxytunnel.exe -v -q -p 127.0.0.1:54450 -r ssh.example.org:80 -d 127.0.0.1:22

Tunneling to ssh.example.org:80 (remote proxy)
Communication with local proxy:
 -> CONNECT ssh.example.org:80 HTTP/1.1
 -> Host: ssh.example.org:80
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.1 200 Connection established

 <-

Tunneling to 127.0.0.1:22 (destination)
Communication with remote proxy:
 -> CONNECT 127.0.0.1:22 HTTP/1.1
 -> Host: 127.0.0.1:22
 -> Proxy-Connection: Keep-Alive
 <- HTTP/1.1 405 Not Allowed

 <- Server: nginx

 <- Date: Fri, 10 May 2024 05:33:10 GMT

 <- Content-Type: text/html

 <- Content-Length: 150

 <- Connection: keep-alive

 <-
```
I saw @yurivict's https://github.com/proxytunnel/proxytunnel/issues/66, so I assume it to be possible. What am I doing wrong? Also tried the same with -X and the equivalent HTTPS config, same result.

**Comment by yurivict** [comment]
"405 Not Allowed" means that nginx rejects the connection.

I used proxytunnel successfully but this was only last year.
I don't quite remember the details.

I have this section from nginx.conf that worked:
```
    server {
     listen       8080 ssl;

     ssl_certificate      /usr/local/etc/nginx/cert/domain.crt; #cert.pem;
     ssl_certificate_key  /usr/local/etc/nginx/cert/domain.key; #cert.key;
     ssl_session_cache    shared:SSL:1m;
    
     # dns resolver used by forward proxying
     resolver                       8.8.8.8;

     # forward proxy for CONNECT request
     proxy_connect;
     proxy_connect_allow            17122; # special ssh port
     proxy_connect_connect_timeout  10s;
     proxy_connect_data_timeout     1000000s;
    
     # forward proxy for non-CONNECT request
     location / {
         proxy_pass http://$host;
         proxy_set_header Host $host;
     }
    }
```

**Comment by quyvsquy** [comment]
is that working?

**Comment by 68420948** [comment]
@quyvsquy,

standard ngnix does not support the HTTP method 'CONNECT', which is what proxytunnel uses to do its job.

The project https://github.com/chobits/ngx_http_proxy_connect_module seems to offer a module which adds the missing support. However, it requires you to build a patched version of ngnix yourself.

**Comment by FrostKiwi** [comment]
There was no issue with nginx or the config, everything was correct from the start. There was an issue with how NixOS for a reason I still don't understand.

There was an update recently, will recheck and conclude this issue

**Comment by FrostKiwi** [comment]
All my issues are solved.

There is definitely a bug spooking around in `proxytunnel` in the specific combination of Having a 2nd Proxy to jump through (first corporate firewall, then nginx for HTTPS encryption to pass packet inspection), having specifically NGINX (via https://github.com/chobits/ngx_http_proxy_connect_module ) be that 2nd jump and the destination parameter `-d` in `proxytunnel`.

For NGINX config nothing more than this (here in NixOS form) is required.
```nix
      virtualHosts = {
        "domain.com" =  {
          extraConfig = ''
            proxy_connect;
            proxy_connect_allow 22;
            proxy_connect_address 127.0.0.1;
          '';
        };
```
`proxy_connect` to enable `HTTP_CONNECT`, `proxy_connect_allow` to restrict the ports that nginx uses, `proxy_connect_address` to restrict to `localhost`.

For some reason though, `-d` behaves differently depending on whether or not nginx is the first or 2nd jump. With no corporate proxy, you will specify `-p domain.com:443` and destination `-d 127.0.0.1:22`. But with there being a corporate firewall and requiring a 2nd jump, the `HOST` in the `HTTP_CONNECT` header changes. This was ok with Apache, but not with nginx and resulted in the error message `HTTP/1.1 405 Not Allowed`, as shown in the OP. For some reason, the destination has to be changed to be `-d domain.com:22`. Then the HOST is correct and the connection lands with the SSH process.

This doesn't make sense and is probably a bug, but this issue specifically is solved.
